/**
 * RAAD PDF Generator Service
 * Generates professional PDF reports from n8n RAAD output.
 */

import PDFDocument from 'pdfkit';

const PRIMARY = '#332f78';
const APPROVE = '#10b981';
const REJECT = '#ef4444';
const AMBER = '#f59e0b';

export interface RaadResult {
  customer_name: string;
  total_revenue?: number;
  revenue_growth?: number;
  itc_available?: number;
  flagged_count?: number;
  compliance_status?: string;
  cash_flow_risk?: string;
  final_credit_limit?: number;
  parameters_used?: Record<string, unknown>;
}

function formatCurrency(val: number | undefined): string {
  if (val == null || typeof val !== 'number') return '—';
  return '₹' + val.toLocaleString('en-IN');
}

function formatPercent(val: number | undefined): string {
  if (val == null || typeof val !== 'number') return '—';
  return val.toFixed(1) + '%';
}

/**
 * Generate a professional RAAD PDF report from n8n output.
 */
export async function generateRaadPdf(data: RaadResult): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk) => chunks.push(chunk));
  const result = new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  const pageWidth = 595.28 - 100;
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });

  doc.rect(0, 0, 595.28, 60).fill(PRIMARY);
  doc.fillColor('#ffffff').fontSize(16).text('RAAD Credit Analysis Report', 50, 18, { width: 280 });
  doc.fontSize(10).text(`Seven Fincorp\n${dateStr}`, 330, 18, { width: 215, align: 'right' });
  doc.fillColor('#000000');

  let y = 90;
  doc.fontSize(22).font('Helvetica-Bold').text(data.customer_name || '—', 50, y);
  y += 36;

  const limit = data.final_credit_limit ?? 0;
  const cashRisk = (data.cash_flow_risk || '').trim();
  const compliance = (data.compliance_status || '').trim();
  const flagged = data.flagged_count ?? 0;

  let badgeText = 'REVIEW REQUIRED';
  let badgeColor = AMBER;
  if (flagged > 5 || cashRisk === 'High Cash Outflow Risk') {
    badgeText = 'REJECT';
    badgeColor = REJECT;
  } else if (limit > 0 && cashRisk !== 'High Cash Outflow Risk' && compliance === 'No issues detected') {
    badgeText = 'APPROVE';
    badgeColor = APPROVE;
  }

  doc.rect(50, y, 120, 32).fillAndStroke(badgeColor, badgeColor);
  doc.fillColor('#ffffff').fontSize(14).font('Helvetica-Bold').text(badgeText, 50, y + 9, { width: 120, align: 'center' });
  doc.fillColor('#000000');
  y += 48;

  doc.fontSize(12).font('Helvetica').text('Recommended Credit Limit', 50, y);
  y += 6;
  doc.fontSize(24).font('Helvetica-Bold').text(formatCurrency(data.final_credit_limit), 50, y);
  y += 40;

  const cardWidth = (pageWidth - 30) / 4;
  const cards = [
    { label: 'Total Revenue', value: formatCurrency(data.total_revenue) },
    { label: 'Revenue Growth', value: formatPercent(data.revenue_growth) },
    { label: 'ITC Available', value: formatCurrency(data.itc_available) },
    { label: 'Flagged Transactions', value: String(flagged) },
  ];
  for (let i = 0; i < cards.length; i++) {
    const x = 50 + i * (cardWidth + 10);
    doc.rect(x, y, cardWidth, 50).stroke('#e5e7eb');
    doc.fontSize(9).fillColor('#6b7280').text(cards[i].label, x + 8, y + 8, { width: cardWidth - 16 });
    doc.fontSize(12).fillColor('#000000').font('Helvetica-Bold').text(cards[i].value, x + 8, y + 28, { width: cardWidth - 16 });
  }
  doc.fillColor('#000000');
  y += 65;

  doc.fontSize(12).font('Helvetica-Bold').text('Risk Summary', 50, y);
  y += 20;
  doc.fontSize(10).font('Helvetica');
  doc.text('Compliance Status: ' + (compliance || '—'), 50, y);
  y += 16;
  const riskColor = cashRisk.includes('High') ? REJECT : cashRisk.includes('Low') || !cashRisk ? APPROVE : AMBER;
  doc.fillColor(riskColor).text('Cash Flow Risk: ' + (cashRisk || '—'));
  doc.fillColor('#000000');
  y += 24;

  if (flagged > 0) {
    doc.fontSize(11).font('Helvetica-Bold').text('Flagged Transaction Details', 50, y);
    y += 16;
    doc.fontSize(10).font('Helvetica').text(`${flagged} transaction(s) flagged for review. Please verify manually.`, 50, y);
    y += 24;
  }

  const footerY = 800;
  doc.fontSize(8).fillColor('#6b7280')
    .text('This report is generated by Seven Fincorp AI. For internal NBFC use only. Valid for 30 days from generation date.', 50, footerY, { width: pageWidth, align: 'center' });
  doc.text('Confidential. Do not distribute outside authorised personnel.', 50, footerY + 14, { width: pageWidth, align: 'center' });
  doc.fillColor('#000000');

  doc.end();
  return result;
}
